# Generated by Django 5.1.7 on 2025-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_preparation', 'In Preparation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')]),
        ),
    ]
