# Generated by Django 5.1.7 on 2025-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='rool',
            field=models.CharField(choices=[('Select', 'Select'), ('Backend Dev', 'Backend Dev'), ('Frontend Dev', 'Frontend Dev'), ('tester', 'tester'), ('Designer', 'Designer')], default='Select', max_length=20),
        ),
    ]
